### PR TITLE
Testing CI

### PR DESCRIPTION
**Pull request by itsjunetime**
This is a PR of a few misc fixes I've been working on that I'm pushing now to test CI and make sure it all works as I'd expect it to.

### CODE REVIEW

**Comment by itsjunetime** [comment]
@Kreijstal I was previously under the impression that `cargo test` ran benchmarks by default, but I guess I was mistaken, so I added the `--benches` flag to make them run (and specified to only run them with the one `adobe_example` pdf so we don't waste time on all the PDFs) but it seems that the benchmark process segfaults at the end of its execution and I can't exactly figure out why.

I'm guessing it's something like a small incompatibility with destructors (or something like them) between the 23.7 version of poppler we're specifying in Cargo.toml and the 23.10 version we're pulling down from gitlab to compile against, but I can't figure out exactly why or how to resolve it (since poppler-rs doesn't compile when specifying version 23.8 and gitlab doesn't seem to host any older versions of the poppler-glib library). Do you have any ideas for how to fix this? If not, I'll try to boot up an ubuntu VM and take a look at this workflow specifically.

**Comment by itsjunetime** [comment]
Oh, nvm - building with boost worked I guess. I'll merge this now, I think

**Comment by itsjunetime** [comment]
Nevermind again - it looks like that was just a fluke and it's failing on main now. ugh. Ill open another PR to try to fix it.

**Comment by Kreijstal** [comment]
> @Kreijstal I was previously under the impression that `cargo test` ran benchmarks by default, but I guess I was mistaken, so I added the `--benches` flag to make them run (and specified to only run them with the one `adobe_example` pdf so we don't waste time on all the PDFs) but it seems that the benchmark process segfaults at the end of its execution and I can't exactly figure out why.
> 
> I'm guessing it's something like a small incompatibility with destructors (or something like them) between the 23.7 version of poppler we're specifying in Cargo.toml and the 23.10 version we're pulling down from gitlab to compile against, but I can't figure out exactly why or how to resolve it (since poppler-rs doesn't compile when specifying version 23.8 and gitlab doesn't seem to host any older versions of the poppler-glib library). Do you have any ideas for how to fix this? If not, I'll try to boot up an ubuntu VM and take a look at this workflow specifically.

I think you can just specify a lower version of poppler, no?

**Pull request merged**
